<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../ModularMonolith.Modules.Auth.Contracts/ModularMonolith.Modules.Auth.Contracts.csproj" />
    <ProjectReference Include="../../../Shared/ModularMonolith.Shared.Infrastructure/ModularMonolith.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
