name: CI

on:
  push:
    branches: [develop, main]
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - run: dotnet restore ModularMonolith.slnx
      - run: dotnet format ModularMonolith.slnx --verify-no-changes --no-restore
      - run: dotnet build ModularMonolith.slnx --no-restore --configuration Release
      - run: dotnet test ModularMonolith.slnx --no-build --configuration Release
